name: deploy ordering-system-backend
on:
  #监听push操作
  push:
    branches:
      - main
    paths:
      - "ordering-system-backend/**"
jobs:
  build:
    runs-on: ubuntu:23.10

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.20.2"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build:b
        run: pnpm build:b
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "ordering-system-backend/dist/"
          REMOTE_HOST: "81.68.108.130"
          REMOTE_USER: root
          TARGET: "/home/ordering-system/ordering-system-backend"
