name: deploy ordering-system-backend
on:
  #监听push操作
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ordering-system-backend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.20.2"
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        with:
          version: 8.8.0
          run_install: true
      - name: Run build:b
        run: pnpm build:b
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "ordering-system-backend/dist/"
          REMOTE_HOST: "182.92.222.231"
          REMOTE_USER: root
          TARGET: "/home/ordering-system/ordering-system-backend"
